In [2]:
import json
import pandas

In [6]:
# with open("params.json", "r") as file:
#     data = json.load(file)

filepath = r"Z:\Dropbox\CurrentClasses\graduate_project\AOI\UpdatedGraphAOI.tsv"
df = pandas.read_csv(filepath, index_col=False, sep="\t")
df

,GraphType,QuestionTL,QuestionBL,QuestionTR,QuestionBR,TitleTL,TitleBL,TitleTR,TitleBR,LabelBoxTL,...,XAxisTR,XAxisBR,YAxisTL,YAxisBL,YAxisTR,YAxisBR,GraphTL,GraphBL,GraphTR,GraphBR
0,HighBar,"248,91","248,124","1673,91","1,673,124","371,189","371,210","854,189","854,210","1223, 226",...,"1,180,833","1,180,858","41,234","41,800","95,234","95,800","114,227","114,831","1250, 227","1250, 831"
1,LowBar,"457,94","457,126","1459, 94","1,459,126","260,187","260, 212","1090, 187","1090, 212","1234, 237",...,"1189, 838","1189, 854","74,261","74,839","112,261","112,839","142,230","142,831","1220, 230","1,220,831"
2,HighLine,"411,93","411, 126","1510,93","1510, 126","378,189","378,210","844,189","844,210","1224, 228",...,"1171, 835","1171, 857","41,229","41,822","91,229","91,822","93,229","93,832","1129, 229","1129, 832"
3,LowLine,"399,92","399,127","1516,92","1516, 127","330,189","330,210","894,189","894,210","1224, 227",...,"1167, 837","1167, 837","45,268","45,804","89,268","89,804","95,228","95,830","1125, 228","1125, 830"

In [4]:
dict1 = {}
columns = df.columns.values
print(columns)

for index, col in df.iterrows():
    graph_type = col["GraphType"]
    dict2 = {}
    # Every 4 reading: top left, bottom left, top right, bottom right
    max_len = len(col)
    for i in range(1, max_len, 4):
        # Dictionary key will be the label of the AOI
        aoi_label = columns[i][:-2]
        # Top Left (x, y) coordinates
        top_left = [a.strip() for a in col[i].split(",")]
        if len(top_left) > 2:
            raise ValueError("There should only be two values")
        top_left = ",".join(top_left)
        # Bottom left (x, y) coordinates
        bot_left = [a.strip() for a in col[i + 1].split(",")]
        if len(bot_left) > 2:
            raise ValueError("There should only be two values")
        bot_left = ",".join(bot_left)
        # Top Right (x, y) coordinates
        top_right = [a.strip() for a in col[i + 2].split(",")]
        if len(top_right) > 2:
            raise ValueError("There should only be two values")
        top_right = ",".join(top_right)
        # Bot Right (x, y) coordinates
        bot_right = [a.strip() for a in col[i + 3].split(",")]
        if len(bot_right) > 2:
            raise ValueError("There should only be two values")
        bot_right = ",".join(bot_right)
        
        dict2[aoi_label] = [top_left, bot_left, top_right, bot_right]
    dict1[graph_type] = dict2
    
print(json.dumps(dict1, indent=2))

# with open("blah2.json", "w") as file:
#     json.dump(dict1, file, indent=2)

['GraphType' 'QuestionTL' 'QuestionBL' 'QuestionTR' 'QuestionBR' 'TitleTL'
 'TitleBL' 'TitleTR' 'TitleBR' 'LabelBoxTL' 'LabelBoxBL' 'LabelBoxTR'
 'LabelBoxBR' 'OptionBoxTL' 'OptionBoxBL' 'OptionBoxTR' 'OptionBoxBR'
 'AnswersTL' 'AnswersBL' 'AnswersTR' 'AnswersBR' 'XAxisTL' 'XAxisBL'
 'XAxisTR' 'XAxisBR' 'YAxisTL' 'YAxisBL' 'YAxisTR' 'YAxisBR' 'GraphTL'
 'GraphBL' 'GraphTR' 'GraphBR']

ValueError: There should only be two values